config/routes.rb
Perds::Application.routes.draw do

  get  "informe/index"
  get  "upload/index"
  post "upload/procesa"

  resources :datos

  resources :tdatos

  resources :areas

  resources :empresas

    root :to => "informe#index"

end

app/models/tdato.rb
class Tdato < ActiveRecord::Base
	has_many :datos
end

app/controllers/tdatos_controller.rb
class TdatosController < ApplicationController
  # GET /tdatos
  # GET /tdatos.xml
  def index
    @tdatos = Tdato.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tdatos }
    end
  end

  # GET /tdatos/1
  # GET /tdatos/1.xml
  def show
    @tdato = Tdato.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tdato }
    end
  end

  # GET /tdatos/new
  # GET /tdatos/new.xml
  def new
    @tdato = Tdato.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tdato }
    end
  end

  # GET /tdatos/1/edit
  def edit
    @tdato = Tdato.find(params[:id])
  end

  # POST /tdatos
  # POST /tdatos.xml
  def create
    @tdato = Tdato.new(params[:tdato])

    respond_to do |format|
      if @tdato.save
        format.html { redirect_to(@tdato, :notice => 'Tdato was successfully created.') }
        format.xml  { render :xml => @tdato, :status => :created, :location => @tdato }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tdato.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tdatos/1
  # PUT /tdatos/1.xml
  def update
    @tdato = Tdato.find(params[:id])

    respond_to do |format|
      if @tdato.update_attributes(params[:tdato])
        format.html { redirect_to(@tdato, :notice => 'Tdato was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tdato.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tdatos/1
  # DELETE /tdatos/1.xml
  def destroy
    @tdato = Tdato.find(params[:id])
    @tdato.destroy

    respond_to do |format|
      format.html { redirect_to(tdatos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tdatos_helper.rb
module TdatosHelper
end

app/views/tdatos/_form.html.erb
<%= form_for(@tdato) do |f| %>
  <% if @tdato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tdato.errors.count, "error") %> prohibited this tdato from being saved:</h2>

      <ul>
      <% @tdato.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tdatos/edit.html.erb
<h1>Editing tdato</h1>

<%= render 'form' %>

<%= link_to 'Show', @tdato %> |
<%= link_to 'Back', tdatos_path %>

app/views/tdatos/index.html.erb
<h1>Listing tdatos</h1>

<table>
  <tr>
    <th>Tipo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tdatos.each do |tdato| %>
  <tr>
    <td><%= tdato.tipo %></td>
    <td><%= link_to 'Show', tdato %></td>
    <td><%= link_to 'Edit', edit_tdato_path(tdato) %></td>
    <td><%= link_to 'Destroy', tdato, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tdato', new_tdato_path %>

app/views/tdatos/new.html.erb
<h1>New tdato</h1>

<%= render 'form' %>

<%= link_to 'Back', tdatos_path %>

app/views/tdatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tipo:</b>
  <%= @tdato.tipo %>
</p>


<%= link_to 'Edit', edit_tdato_path(@tdato) %> |
<%= link_to 'Back', tdatos_path %>