config/routes.rb
Perds::Application.routes.draw do

  get  "informe/index"
  get  "upload/index"
  post "upload/procesa"

  resources :datos

  resources :tdatos

  resources :areas

  resources :empresas

    root :to => "informe#index"

end

app/models/dato.rb
class Dato < ActiveRecord::Base
	belongs_to :empresa
	belongs_to :area
	belongs_to :tdato
end

app/controllers/datos_controller.rb
class DatosController < ApplicationController
  # GET /datos
  # GET /datos.xml
  def index
    @datos = Dato.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @datos }
    end
  end

  # GET /datos/1
  # GET /datos/1.xml
  def show
    @dato = Dato.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dato }
    end
  end

  # GET /datos/new
  # GET /datos/new.xml
  def new
    @dato = Dato.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dato }
    end
  end

  # GET /datos/1/edit
  def edit
    @dato = Dato.find(params[:id])
  end

  # POST /datos
  # POST /datos.xml
  def create
    @dato = Dato.new(params[:dato])

    respond_to do |format|
      if @dato.save
        format.html { redirect_to(@dato, :notice => 'Dato was successfully created.') }
        format.xml  { render :xml => @dato, :status => :created, :location => @dato }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dato.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /datos/1
  # PUT /datos/1.xml
  def update
    @dato = Dato.find(params[:id])

    respond_to do |format|
      if @dato.update_attributes(params[:dato])
        format.html { redirect_to(@dato, :notice => 'Dato was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dato.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /datos/1
  # DELETE /datos/1.xml
  def destroy
    @dato = Dato.find(params[:id])
    @dato.destroy

    respond_to do |format|
      format.html { redirect_to(datos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/datos_helper.rb
module DatosHelper
end

app/views/datos/_form.html.erb
<%= form_for(@dato) do |f| %>
  <% if @dato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dato.errors.count, "error") %> prohibited this dato from being saved:</h2>

      <ul>
      <% @dato.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :empresa_id %><br />
    <%= f.text_field :empresa_id %>
  </div>
  <div class="field">
    <%= f.label :tdato_id %><br />
    <%= f.text_field :tdato_id %>
  </div>
  <div class="field">
    <%= f.label :periodo %><br />
    <%= f.date_select :periodo %>
  </div>
  <div class="field">
    <%= f.label :area_id %><br />
    <%= f.text_field :area_id %>
  </div>
  <div class="field">
    <%= f.label :dato %><br />
    <%= f.text_field :dato %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/datos/edit.html.erb
<h1>Editing dato</h1>

<%= render 'form' %>

<%= link_to 'Show', @dato %> |
<%= link_to 'Back', datos_path %>

app/views/datos/index.html.erb
<h1>Listing datos</h1>

<table>
  <tr>
    <th>Empresa</th>
    <th>Tdato</th>
    <th>Periodo</th>
    <th>Area</th>
    <th>Dato</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @datos.each do |dato| %>
  <tr>
    <td><%= dato.empresa_id %></td>
    <td><%= dato.tdato_id %></td>
    <td><%= dato.periodo %></td>
    <td><%= dato.area_id %></td>
    <td><%= dato.dato %></td>
    <td><%= link_to 'Show', dato %></td>
    <td><%= link_to 'Edit', edit_dato_path(dato) %></td>
    <td><%= link_to 'Destroy', dato, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dato', new_dato_path %>

app/views/datos/new.html.erb
<h1>New dato</h1>

<%= render 'form' %>

<%= link_to 'Back', datos_path %>

app/views/datos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Empresa:</b>
  <%= @dato.empresa_id %>
</p>

<p>
  <b>Tdato:</b>
  <%= @dato.tdato_id %>
</p>

<p>
  <b>Periodo:</b>
  <%= @dato.periodo %>
</p>

<p>
  <b>Area:</b>
  <%= @dato.area_id %>
</p>

<p>
  <b>Dato:</b>
  <%= @dato.dato %>
</p>


<%= link_to 'Edit', edit_dato_path(@dato) %> |
<%= link_to 'Back', datos_path %>