config/routes.rb
Perds::Application.routes.draw do

  get  "informe/index"
  get  "upload/index"
  post "upload/procesa"

  resources :datos

  resources :tdatos

  resources :areas

  resources :empresas

    root :to => "informe#index"

end

app/models/area.rb
class Area < ActiveRecord::Base
	belongs_to :empresa
	has_many :datos
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  # GET /areas
  # GET /areas.xml
  def index
    @areas = Area.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @areas }
    end
  end

  # GET /areas/1
  # GET /areas/1.xml
  def show
    @area = Area.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @area }
    end
  end

  # GET /areas/new
  # GET /areas/new.xml
  def new
    @area = Area.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @area }
    end
  end

  # GET /areas/1/edit
  def edit
    @area = Area.find(params[:id])
  end

  # POST /areas
  # POST /areas.xml
  def create
    @area = Area.new(params[:area])

    respond_to do |format|
      if @area.save
        format.html { redirect_to(@area, :notice => 'Area was successfully created.') }
        format.xml  { render :xml => @area, :status => :created, :location => @area }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @area.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /areas/1
  # PUT /areas/1.xml
  def update
    @area = Area.find(params[:id])

    respond_to do |format|
      if @area.update_attributes(params[:area])
        format.html { redirect_to(@area, :notice => 'Area was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @area.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.xml
  def destroy
    @area = Area.find(params[:id])
    @area.destroy

    respond_to do |format|
      format.html { redirect_to(areas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :empresa_id %><br />
    <%= f.text_field :empresa_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing area</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<h1>Listing areas</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Empresa</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @areas.each do |area| %>
  <tr>
    <td><%= area.nombre %></td>
    <td><%= area.empresa_id %></td>
    <td><%= link_to 'Show', area %></td>
    <td><%= link_to 'Edit', edit_area_path(area) %></td>
    <td><%= link_to 'Destroy', area, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @area.nombre %>
</p>

<p>
  <b>Empresa:</b>
  <%= @area.empresa_id %>
</p>


<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>